export interface LegalDocument {
  id: string;
  date: string;
  title: string;
  description: string;
  filename: string;
  fileSize: string;
  category: 'complaint' | 'answer' | 'motion' | 'order' | 'notice' | 'service' | 'discovery' | 'affidavit' | 'stipulation' | 'protective-order' | 'docket' | 'pretrial';
  significance: string;
  parties?: string[];
}

export interface TimelineEvent {
  id: string;
  date: string;
  title: string;
  description: string;
  documentId?: string;
  type: 'filing' | 'order' | 'hearing' | 'deadline';
}

export const legalDocuments: LegalDocument[] = [
  // Complete Case Docket
  {
    id: 'case-docket-complete',
    date: '2026-02-01',
    title: 'Complete Case Docket History',
    description: 'Comprehensive court docket showing all filings, orders, and proceedings from case inception through January 2026.',
    filename: 'case-docket-history-complete.pdf',
    fileSize: '894 KB',
    category: 'docket',
    significance: 'Official record of all case activities, providing complete transparency of the legal proceedings. Case No. 24-498, Miami County Ohio Court of Common Pleas.',
    parties: ['All Parties'],
  },

  // Initial Complaint and Summons (October 2024)
  {
    id: 'complaint-filed-2024-10-24',
    date: '2024-10-24',
    title: 'Original Complaint Filed',
    description: 'The Other Woman and the Wife LLC\'s original complaint against Kristen Jacobs initiating the lawsuit.',
    filename: 'complaint-filed-2024-06-06.pdf',
    fileSize: '225 KB',
    category: 'complaint',
    significance: 'Initial pleading that started the lawsuit, outlining plaintiff\'s allegations and legal claims. Case No. 24 CV 00498.',
    parties: ['The Other Woman and the Wife LLC', 'Kristen Jacobs'],
  },
  {
    id: 'summons-issued-2024-10-25',
    date: '2024-10-25',
    title: 'Summons Issued',
    description: 'Court-issued summons notifying Kristen Jacobs of the lawsuit and requiring a response.',
    filename: 'summons-issued-2024-06-06.pdf',
    fileSize: '56 KB',
    category: 'notice',
    significance: 'Official court notice beginning the legal process and establishing timeline for response.',
    parties: ['Court', 'Kristen Jacobs'],
  },

  // Service of Process Documents (October-November 2024)
  {
    id: 'request-service-by-mail-2024-10',
    date: '2024-10-24',
    title: 'Request for Service by Mail',
    description: 'Plaintiff\'s request to serve Kristen Jacobs via certified mail.',
    filename: 'request-service-by-mail-2024-06.pdf',
    fileSize: '34 KB',
    category: 'service',
    significance: 'Initiates service of process through U.S. Mail method.',
    parties: ['The Other Woman and the Wife LLC'],
  },
  {
    id: 'praecipe-for-service-2024-11',
    date: '2024-11-08',
    title: 'Praecipe for Service',
    description: 'Written request to the clerk of court to issue process for service.',
    filename: 'praecipe-for-service-2024-06.pdf',
    fileSize: '125 KB',
    category: 'service',
    significance: 'Formal request directing court clerk to prepare documents for service.',
    parties: ['The Other Woman and the Wife LLC'],
  },
  {
    id: 'certificate-of-mailing-2024-11',
    date: '2024-11-13',
    title: 'Certificate of Mailing',
    description: 'Certification that summons and complaint were mailed to defendant.',
    filename: 'certificate-of-mailing-2024-06.pdf',
    fileSize: '36 KB',
    category: 'service',
    significance: 'Documents attempt to serve defendant through certified mail.',
    parties: ['The Other Woman and the Wife LLC'],
  },
  {
    id: 'certificate-mailing-failed-2024-11',
    date: '2024-11-04',
    title: 'Certificate of Mailing Failed',
    description: 'Notification that certified mail service attempt was unsuccessful - unclaimed.',
    filename: 'certificate-mailing-failed-2024-06.pdf',
    fileSize: '38 KB',
    category: 'service',
    significance: 'Documents failed service attempt, requiring alternative service method.',
    parties: ['The Other Woman and the Wife LLC'],
  },
  {
    id: 'notice-of-failure-to-serve-2024-11',
    date: '2024-11-05',
    title: 'Notice of Failure to Serve',
    description: 'Court notice documenting the failure to successfully serve defendant.',
    filename: 'notice-of-failure-to-serve-2024-06.pdf',
    fileSize: '32 KB',
    category: 'service',
    significance: 'Official court record of service difficulties.',
    parties: ['Court'],
  },
  {
    id: 'instructions-for-service-2024-12',
    date: '2024-12-06',
    title: 'Instructions for Service',
    description: 'Detailed instructions for properly serving the defendant.',
    filename: 'instructions-for-service-2024-06.pdf',
    fileSize: '84 KB',
    category: 'service',
    significance: 'Provides guidance on proper service procedures after initial failure.',
    parties: ['Court'],
  },

  // Successful Service and Response (December 2024)
  {
    id: 'return-of-service-2024-12',
    date: '2024-12-13',
    title: 'Return of Service',
    description: 'Confirmation that third-party defendants were successfully served with counterclaims.',
    filename: 'return-of-service-2024-07.pdf',
    fileSize: '40 KB',
    category: 'service',
    significance: 'Documents successful service of process on Olivia Nicodemus.',
    parties: ['Kristen Jacobs'],
  },
  {
    id: 'answer-and-counterclaims-2024-12-06',
    date: '2024-12-06',
    title: 'Answer and Counterclaims',
    description: 'Kristen Jacobs\' response to the complaint, denying allegations and asserting counterclaims and third-party complaint.',
    filename: 'answer-and-counterclaims-2024-07-03.pdf',
    fileSize: '45 KB',
    category: 'answer',
    significance: 'Kristen\'s formal legal defense and offensive counterclaims against plaintiff, plus third-party claims against Chelsea Smallwood and Olivia Nicodemus.',
    parties: ['Kristen Jacobs'],
  },
  {
    id: 'notice-of-appearance-2024-12',
    date: '2024-12-20',
    title: 'Notice of Appearance',
    description: 'Attorney\'s formal notice of representation for third-party defendant Olivia Nicodemus.',
    filename: 'notice-of-appearance-2024-07.pdf',
    fileSize: '195 KB',
    category: 'notice',
    significance: 'Establishes legal counsel for Olivia Nicodemus.',
    parties: ['Alexander W. Cloonan', 'Olivia Nicodemus'],
  },

  // Arbitration Dispute (December 2024)
  {
    id: 'motion-compel-arbitration-2024-12-06',
    date: '2024-12-06',
    title: 'Motion to Compel Arbitration or Stay',
    description: 'Defendant Kristen Jacobs\' motion seeking to force the dispute into arbitration rather than court, or stay proceedings.',
    filename: 'motion-compel-arbitration-2024.pdf',
    fileSize: '253 KB',
    category: 'motion',
    significance: 'Attempt to move case out of court system into private arbitration based on contractual agreement.',
    parties: ['Kristen Jacobs'],
  },
  {
    id: 'motion-arbitrate-or-stay-2024-12-06',
    date: '2024-12-06',
    title: 'Motion to Arbitrate or Stay',
    description: 'Alternative motion requesting either arbitration or stay of court proceedings.',
    filename: 'motion-arbitrate-or-stay-2024.pdf',
    fileSize: '267 KB',
    category: 'motion',
    significance: 'Seeks to pause or redirect the litigation process.',
    parties: ['Kristen Jacobs'],
  },
  {
    id: 'reply-compel-arbitration-2024-12-27',
    date: '2024-12-27',
    title: 'Reply in Support of Motion to Compel Arbitration',
    description: 'Kristen Jacobs\' reply brief supporting her motion to compel arbitration.',
    filename: 'reply-compel-arbitration-2024.pdf',
    fileSize: '426 KB',
    category: 'motion',
    significance: 'Additional legal arguments supporting arbitration, responding to plaintiff\'s opposition.',
    parties: ['Kristen Jacobs'],
  },
  {
    id: 'order-deny-arbitration-2025-02-24',
    date: '2025-02-24',
    title: 'Decision and Judgment Entry Denying Motion to Compel Arbitration',
    description: 'Court order rejecting defendant\'s motion to compel arbitration.',
    filename: 'order-deny-arbitration-2025.pdf',
    fileSize: '241 KB',
    category: 'order',
    significance: 'Court rules that case will proceed in court system, not through arbitration. Significant procedural victory for plaintiff.',
    parties: ['Court', 'Judge Stacy M. Wall'],
  },

  // Counterclaim Activity (January 2025)
  {
    id: 'tow-counterclaim-2025-01-03',
    date: '2025-01-03',
    title: 'Plaintiff\'s Answer to Defendant\'s Counterclaim',
    description: 'The Other Woman and the Wife LLC and Chelsea Smallwood\'s answer to Kristen Jacobs\' counterclaims.',
    filename: 'tow-counterclaim-2025.pdf',
    fileSize: '253 KB',
    category: 'answer',
    significance: 'Plaintiff responds to defendant\'s counterclaims, denying allegations.',
    parties: ['The Other Woman and the Wife LLC', 'Chelsea Smallwood'],
  },
  {
    id: 'unopposed-counterclaim-motion-2025-02-24',
    date: '2025-02-24',
    title: 'Unopposed Motion for Leave to File Redacted Portions',
    description: 'Kristen Jacobs\' unopposed motion to file redacted portions of the third-party complaint.',
    filename: 'unopposed-counterclaim-motion-2025.pdf',
    fileSize: '535 KB',
    category: 'motion',
    significance: 'Uncontested motion to protect sensitive information while maintaining transparency.',
    parties: ['Kristen Jacobs'],
  },
  {
    id: 'tow-leave-to-amend-2025-01',
    date: '2025-01-15',
    title: 'Leave to Amend Pleadings',
    description: 'Motion seeking permission to modify pleadings.',
    filename: 'tow-leave-to-amend-2025.pdf',
    fileSize: '1.3 MB',
    category: 'motion',
    significance: 'Request to update or change complaint or counterclaims. (Note: Exact filing date not clearly identified in docket)',
    parties: ['The Other Woman and the Wife LLC'],
  },

  // Discovery and Evidence (January-December 2025)
  {
    id: 'stipulation-time-extension-2025-01-10',
    date: '2025-01-10',
    title: 'Stipulation for Time Extension',
    description: 'Agreed request by both parties for additional time for discovery.',
    filename: 'stipulation-time-extension-2025.pdf',
    fileSize: '97 KB',
    category: 'stipulation',
    significance: 'Shows parties working cooperatively to manage case timeline.',
    parties: ['All Parties'],
  },
  {
    id: 'second-stipulation-extension-2025-01-22',
    date: '2025-01-22',
    title: 'Second Stipulation for Extension of Time',
    description: 'Second agreed request for additional time for Olivia Nicodemus to answer third-party complaint.',
    filename: 'second-stipulation-extension-2025.pdf',
    fileSize: '97 KB',
    category: 'stipulation',
    significance: 'Additional time granted for third-party defendant to respond.',
    parties: ['Kristen Jacobs', 'Olivia Nicodemus'],
  },
  {
    id: 'affidavit-chelsea-smallwood-2024-12-20',
    date: '2024-12-20',
    title: 'Affidavit of Chelsea Smallwood',
    description: 'Sworn statement by Chelsea Smallwood regarding case facts, filed in opposition to arbitration motion.',
    filename: 'affidavit-chelsea-smallwood-2025.pdf',
    fileSize: '3.8 MB',
    category: 'affidavit',
    significance: 'Sworn testimony under penalty of perjury from key party, supporting plaintiff\'s opposition to arbitration.',
    parties: ['Chelsea Smallwood'],
  },
  {
    id: 'notice-filing-affidavit-2024-12-20',
    date: '2024-12-20',
    title: 'Notice of Filing Affidavit',
    description: 'Notification to court and parties that Chelsea Smallwood\'s affidavit has been filed.',
    filename: 'notice-filing-affidavit-2025.pdf',
    fileSize: '202 KB',
    category: 'notice',
    significance: 'Documents submission of sworn testimony to the court.',
    parties: ['The Other Woman and the Wife LLC', 'Michael W. Sandner'],
  },
  {
    id: 'protective-order-2025-06-17',
    date: '2025-06-17',
    title: 'Stipulated Protective Order',
    description: 'Court-approved protective order governing disclosure of confidential information during discovery.',
    filename: 'stipulated-protective-order-2025-06-17.pdf',
    fileSize: '2.4 MB',
    category: 'protective-order',
    significance: 'Establishes rules for handling sensitive documents and information shared during the legal discovery process.',
    parties: ['All Parties'],
  },
  {
    id: 'subpoenas-2025-09-18',
    date: '2025-09-18',
    title: 'Notice of Service of Subpoenas',
    description: 'Kristen Jacobs\' notice to the court regarding subpoenas served to Olivia Nicodemus and Julie Von Tersch.',
    filename: 'notice-of-service-subpoenas-2025-09-18.pdf',
    fileSize: '7.4 MB',
    category: 'discovery',
    significance: 'Documents the formal request for testimony and evidence from key witnesses in the case.',
    parties: ['Kristen Jacobs', 'Olivia Nicodemus', 'Julie Von Tersch'],
  },

  // Counsel Changes (February 2025)
  {
    id: 'motion-substitution-counsel-2025-02-18',
    date: '2025-02-18',
    title: 'Motion for Substitution of Counsel',
    description: 'Request to replace current attorney with new legal representation.',
    filename: 'motion-substitution-counsel-2025.pdf',
    fileSize: '55 KB',
    category: 'motion',
    significance: 'Seeks court approval for change in legal representation.',
    parties: ['Anthony V. Graber'],
  },
  {
    id: 'order-granting-substitution-counsel-2025-02-20',
    date: '2025-02-20',
    title: 'Proposed Order Granting Substitution of Counsel',
    description: 'Court approves the change in legal representation.',
    filename: 'order-granting-substitution-counsel-2025.pdf',
    fileSize: '1.9 MB',
    category: 'order',
    significance: 'Confirms new attorney may represent party in the case.',
    parties: ['Court', 'Judge Stacy M. Wall'],
  },

  // Redaction and Privacy (February-March 2025)
  {
    id: 'notice-filing-redacted-2025-03-07',
    date: '2025-03-07',
    title: 'Notice of Filing Redacted Answer and Counterclaim',
    description: 'Notification that redacted version of Kristen Jacobs\' answer and third-party complaint has been filed.',
    filename: 'notice-filing-redacted-2025.pdf',
    fileSize: '574 KB',
    category: 'notice',
    significance: 'Protects privacy while maintaining transparency in court proceedings.',
    parties: ['Kristen Jacobs', 'Morgan K. Napier'],
  },
  {
    id: 'order-granting-redaction-2025-02-25',
    date: '2025-02-25',
    title: 'Order Granting Leave to File Redacted Portions',
    description: 'Court approves Kristen Jacobs\' motion to redact sensitive information from third-party complaint.',
    filename: 'order-granting-redaction-2025.pdf',
    fileSize: '1.3 MB',
    category: 'order',
    significance: 'Balances public transparency with privacy protection.',
    parties: ['Court'],
  },

  // Witness Dismissal (February 2025)
  {
    id: 'notice-dismissal-olivia-2025-02-19',
    date: '2025-02-19',
    title: 'Notice of Dismissal of Third-Party Defendant Olivia Nicodemus',
    description: 'Kristen Jacobs\' notice that claims against Olivia Nicodemus are being dismissed with prejudice.',
    filename: 'notice-dismissal-olivia-2025.pdf',
    fileSize: '77 KB',
    category: 'notice',
    significance: 'Voluntarily removes Olivia Nicodemus from the case.',
    parties: ['Kristen Jacobs', 'Olivia Nicodemus'],
  },
  {
    id: 'order-dismissal-olivia-2025-02-19',
    date: '2025-02-19',
    title: 'Dismissal of Third-Party Defendant Olivia Nicodemus',
    description: 'Dismissal of all claims against Olivia Nicodemus with prejudice (cannot be refiled).',
    filename: 'order-dismissal-olivia-2025.pdf',
    fileSize: '79 KB',
    category: 'order',
    significance: 'Olivia Nicodemus is no longer a party to the lawsuit. Disposition date: 02/19/2025.',
    parties: ['Court', 'Olivia Nicodemus'],
  },

  // Pre-Trial and Settlement (May-June 2025)
  {
    id: 'scheduling-order-2025-05-28',
    date: '2025-05-28',
    title: 'Scheduling Order',
    description: 'Court order establishing deadlines and procedures for case progression through trial.',
    filename: 'scheduling-order-2025.pdf',
    fileSize: '52 KB',
    category: 'pretrial',
    significance: 'Sets timeline for discovery, expert disclosures, motions, and trial preparation.',
    parties: ['Court', 'Judge Stacy M. Wall'],
  },
  {
    id: 'order-of-appearance-filed-2025-03-04',
    date: '2025-03-04',
    title: 'Order of Appearance - Margo S. Brandenburg',
    description: 'Court order documenting attorney Margo S. Brandenburg\'s appearance for Chelsea Smallwood.',
    filename: 'order-of-appearance-filed-2025.pdf',
    fileSize: '453 KB',
    category: 'order',
    significance: 'Official record of legal representation for third-party defendant Chelsea Smallwood.',
    parties: ['Court', 'Margo S. Brandenburg', 'Chelsea Smallwood'],
  },
  {
    id: 'notice-settlement-conference-2025-05-28',
    date: '2025-05-28',
    title: 'Notice of Settlement Conference',
    description: 'Notification of court-ordered settlement conference scheduled for May 1, 2026.',
    filename: 'notice-settlement-conference-2025.pdf',
    fileSize: '133 KB',
    category: 'pretrial',
    significance: 'Court facilitates settlement discussions before trial. Conference set for 5/1/26 @ 9:30am.',
    parties: ['Court', 'All Parties'],
  },
  {
    id: 'final-pretrial-conference-2025-05-28',
    date: '2025-05-28',
    title: 'Final Pre-Trial Conference Notice',
    description: 'Notice of final pretrial conference scheduled for May 15, 2026.',
    filename: 'final-pretrial-conference-2025.pdf',
    fileSize: '51 KB',
    category: 'pretrial',
    significance: 'Final preparation meeting before trial begins. Conference set for 5/15/26 @ 9:00am.',
    parties: ['Court', 'All Parties'],
  },
  {
    id: 'trial-procedures-2025-05-28',
    date: '2025-05-28',
    title: 'Trial Procedures Order',
    description: 'Court\'s rules and procedures for conducting the jury trial scheduled for June 2, 2026.',
    filename: 'trial-procedures-2025.pdf',
    fileSize: '140 KB',
    category: 'pretrial',
    significance: 'Establishes rules for trial conduct and evidence presentation. Jury trial set for 6/2/26 @ 9:00am.',
    parties: ['Court', 'Judge Stacy M. Wall'],
  },

  // Joint Motions for Extension (September 2025)
  {
    id: 'motion-extension-2025-09-25',
    date: '2025-09-25',
    title: 'Joint Motion for Extension of Deadline',
    description: 'Both parties request additional time to complete expert disclosures and exchange expert reports.',
    filename: 'joint-motion-extension-2025-09-25.pdf',
    fileSize: '151 KB',
    category: 'motion',
    significance: 'Shows both sides working cooperatively to ensure thorough expert analysis before proceeding.',
    parties: ['Plaintiffs', 'Defendants'],
  },
  {
    id: 'order-granting-extension-2025-09-25',
    date: '2025-09-25',
    title: 'Order Granting Joint Motion for Extension',
    description: 'Judge Stacy M. Wall approves the extension request, granting additional time for expert disclosures.',
    filename: 'granting-joint-motion-2025-09-25.pdf',
    fileSize: '65 KB',
    category: 'order',
    significance: 'Court approval ensures both parties have adequate time to prepare their expert evidence.',
    parties: ['Court'],
  },

  // New Counsel and Motions (October-November 2025)
  {
    id: 'notice-appearance-stewart-2025-10-20',
    date: '2025-10-20',
    title: 'Notice of Appearance - Dalton L. Stewart',
    description: 'Attorney Dalton L. Stewart files notice of appearance as co-counsel for defendant Kristen Jacobs, joining Morgan K. Napier.',
    filename: 'notice-appearance-stewart-2025.pdf',
    fileSize: '85 KB',
    category: 'notice',
    significance: 'Kristen Jacobs adds a second attorney to her legal team, signaling increased legal resources for defense.',
    parties: ['Dalton L. Stewart', 'Kristen Jacobs'],
  },
  {
    id: 'motion-extension-counseling-records-2025-10-28',
    date: '2025-10-28',
    title: 'Unopposed Motion for Extension of Counseling Records Deadline',
    description: 'Unopposed motion requesting extension of the deadline for Stacy Pettit to produce Kristen Jacobs\' counseling records.',
    filename: 'motion-extension-counseling-records-2025.pdf',
    fileSize: '120 KB',
    category: 'motion',
    significance: 'Seeks additional time to obtain counseling records relevant to the case. Unopposed indicates agreement between parties.',
    parties: ['Kristen Jacobs', 'Morgan K. Napier'],
  },
  {
    id: 'joint-motion-amend-pretrial-2025-10-31',
    date: '2025-10-31',
    title: 'Joint Motion to Amend Pretrial Order',
    description: 'Joint motion filed by both parties to amend the pretrial order.',
    filename: 'joint-motion-amend-pretrial-2025.pdf',
    fileSize: '95 KB',
    category: 'motion',
    significance: 'Both parties cooperatively request changes to the pretrial schedule and procedures.',
    parties: ['All Parties'],
  },
  {
    id: 'order-extension-counseling-records-2025-10-31',
    date: '2025-10-31',
    title: 'Order Granting Extension for Counseling Records',
    description: 'Court grants unopposed motion extending deadline for Stacy Pettit to produce Kristen Jacobs\' counseling records.',
    filename: 'order-extension-counseling-records-2025.pdf',
    fileSize: '60 KB',
    category: 'order',
    significance: 'Additional time granted for production of counseling records in discovery.',
    parties: ['Court', 'Judge Stacy M. Wall'],
  },
  {
    id: 'order-amend-pretrial-2025-11-03',
    date: '2025-11-03',
    title: 'Order Granting Joint Motion to Amend Pretrial Order',
    description: 'Court approves the joint motion to amend the pretrial order.',
    filename: 'order-amend-pretrial-2025.pdf',
    fileSize: '58 KB',
    category: 'order',
    significance: 'Pretrial order modified by agreement of all parties with court approval.',
    parties: ['Court', 'Judge Stacy M. Wall'],
  },

  // Partial Dismissal (December 2025)
  {
    id: 'notice-partial-dismissal-2025-12-02',
    date: '2025-12-02',
    title: 'Notice of Partial Dismissal of Counterclaims and Cross-Claims',
    description: 'Kristen Jacobs files notice of partial dismissal of her counterclaims and cross-claims, voluntarily dropping some of her claims against the opposing parties.',
    filename: 'notice-partial-dismissal-counterclaims-2025.pdf',
    fileSize: '135 KB',
    category: 'notice',
    significance: 'Significant development — Kristen is voluntarily narrowing her counterclaims, potentially streamlining the case or reflecting strategic adjustments.',
    parties: ['Kristen Jacobs', 'Morgan K. Napier'],
  },

  // Mediation Stay (January 2026)
  {
    id: 'joint-motion-stay-mediation-2026-01-05',
    date: '2026-01-05',
    title: 'Joint Motion to Stay Case Deadlines Pending Mediation',
    description: 'Joint motion filed requesting the court stay all case deadlines while the parties attempt to resolve the dispute through mediation.',
    filename: 'joint-motion-stay-mediation-2026.pdf',
    fileSize: '110 KB',
    category: 'motion',
    significance: 'Both parties agree to pursue mediation, suggesting willingness to settle outside of trial.',
    parties: ['All Parties'],
  },
  {
    id: 'order-stay-mediation-2026-01-05',
    date: '2026-01-05',
    title: 'Order Granting Stay Pending Mediation',
    description: 'Court grants the joint motion to stay all case deadlines while parties pursue mediation.',
    filename: 'order-stay-mediation-2026.pdf',
    fileSize: '65 KB',
    category: 'order',
    significance: 'Case is now STAYED — all deadlines suspended while parties attempt to resolve the dispute through mediation. This is the current status of the case.',
    parties: ['Court', 'Judge Stacy M. Wall'],
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: 'event-0',
    date: '2024-10-24',
    title: 'Lawsuit Filed',
    description: 'The Other Woman and the Wife LLC files lawsuit against Kristen Jacobs in Miami County Ohio Court of Common Pleas (Case No. 24 CV 00498).',
    documentId: 'complaint-filed-2024-10-24',
    type: 'filing',
  },
  {
    id: 'event-0a',
    date: '2024-10-25',
    title: 'Service Process Initiated',
    description: 'Court issues summons and plaintiff begins attempts to serve Kristen Jacobs via certified mail.',
    documentId: 'summons-issued-2024-10-25',
    type: 'filing',
  },
  {
    id: 'event-0b',
    date: '2024-11-04',
    title: 'Service Attempt Fails',
    description: 'Certified mail service attempt unsuccessful - unclaimed. Court issues notice of failure to serve.',
    documentId: 'certificate-mailing-failed-2024-11',
    type: 'filing',
  },
  {
    id: 'event-0c',
    date: '2024-12-06',
    title: 'Kristen Files Answer, Counterclaims & Motion to Compel Arbitration',
    description: 'Kristen Jacobs files her answer, counterclaims, and third-party complaint against Chelsea Smallwood and Olivia Nicodemus. Also files motion to compel arbitration.',
    documentId: 'answer-and-counterclaims-2024-12-06',
    type: 'filing',
  },
  {
    id: 'event-0d',
    date: '2024-12-20',
    title: 'Chelsea Smallwood Files Affidavit',
    description: 'Chelsea Smallwood files sworn affidavit in opposition to arbitration motion.',
    documentId: 'affidavit-chelsea-smallwood-2024-12-20',
    type: 'filing',
  },
  {
    id: 'event-0e',
    date: '2025-01-03',
    title: 'Plaintiff Answers Counterclaim',
    description: 'TOW LLC and Chelsea Smallwood file answer to Kristen\'s counterclaims.',
    documentId: 'tow-counterclaim-2025-01-03',
    type: 'filing',
  },
  {
    id: 'event-1',
    date: '2025-02-19',
    title: 'Olivia Nicodemus Dismissed',
    description: 'Kristen voluntarily dismisses all claims against third-party defendant Olivia Nicodemus with prejudice.',
    documentId: 'order-dismissal-olivia-2025-02-19',
    type: 'order',
  },
  {
    id: 'event-2',
    date: '2025-02-24',
    title: 'Arbitration Motion Denied',
    description: 'Court denies Kristen\'s motion to compel arbitration. Case will proceed in court. Significant procedural victory for plaintiff.',
    documentId: 'order-deny-arbitration-2025-02-24',
    type: 'order',
  },
  {
    id: 'event-3',
    date: '2025-03-04',
    title: 'New Counsel for Chelsea Smallwood',
    description: 'Attorney Margo S. Brandenburg files order of appearance for third-party defendant Chelsea Smallwood.',
    documentId: 'order-of-appearance-filed-2025-03-04',
    type: 'filing',
  },
  {
    id: 'event-4',
    date: '2025-05-28',
    title: 'Scheduling Order & Trial Dates Set',
    description: 'Court issues scheduling order setting deadlines. Settlement conference set for 5/1/26, final pretrial for 5/15/26, jury trial for 6/2/26.',
    documentId: 'scheduling-order-2025-05-28',
    type: 'order',
  },
  {
    id: 'event-5',
    date: '2025-06-17',
    title: 'Protective Order Approved',
    description: 'Court approves stipulated protective order governing disclosure of confidential information during discovery.',
    documentId: 'protective-order-2025-06-17',
    type: 'order',
  },
  {
    id: 'event-6',
    date: '2025-09-18',
    title: 'Subpoenas Served',
    description: 'Kristen Jacobs files notice of service of subpoenas to key witnesses Olivia Nicodemus and Julie Von Tersch.',
    documentId: 'subpoenas-2025-09-18',
    type: 'filing',
  },
  {
    id: 'event-7',
    date: '2025-09-25',
    title: 'Extension Request Filed & Granted',
    description: 'Joint motion for extension of expert disclosure deadline filed by both parties. Court immediately grants the motion.',
    documentId: 'motion-extension-2025-09-25',
    type: 'order',
  },
  {
    id: 'event-8',
    date: '2025-10-20',
    title: 'New Co-Counsel for Kristen Jacobs',
    description: 'Attorney Dalton L. Stewart files notice of appearance as co-counsel for Kristen Jacobs, joining Morgan K. Napier on the defense team.',
    documentId: 'notice-appearance-stewart-2025-10-20',
    type: 'filing',
  },
  {
    id: 'event-9',
    date: '2025-10-31',
    title: 'Counseling Records Extension Granted',
    description: 'Court grants unopposed motion extending deadline for Stacy Pettit to produce Kristen Jacobs\' counseling records.',
    documentId: 'order-extension-counseling-records-2025-10-31',
    type: 'order',
  },
  {
    id: 'event-10',
    date: '2025-11-03',
    title: 'Pretrial Order Amended',
    description: 'Court grants joint motion to amend the pretrial order by agreement of all parties.',
    documentId: 'order-amend-pretrial-2025-11-03',
    type: 'order',
  },
  {
    id: 'event-11',
    date: '2025-12-02',
    title: 'Kristen Partially Dismisses Counterclaims',
    description: 'Kristen Jacobs files notice of partial dismissal of her counterclaims and cross-claims, voluntarily dropping some of her claims against the opposing parties.',
    documentId: 'notice-partial-dismissal-2025-12-02',
    type: 'filing',
  },
  {
    id: 'event-12',
    date: '2026-01-05',
    title: 'Case Stayed for Mediation',
    description: 'Court grants joint motion to stay all case deadlines while parties pursue mediation. All proceedings suspended as both sides attempt to resolve the dispute outside of trial.',
    documentId: 'order-stay-mediation-2026-01-05',
    type: 'order',
  },
];
